// geofence.characterization.test.js — INTL milestone M0 (characterization / anti-regression net).
//
// PURPOSE (INTERNATIONAL_PLAN.md §5 "M0", §4.0):
//   Freeze the EXACT true/false output of the CURRENT publish geofence,
//   `envVariables.dentroLimites(coords)` in
//   src/app/components/compatibility/components/variaveisAmbiente.js:9-25,
//   so that ANY future refactor (M1's delegation to a country-aware predicate)
//   that changes even ONE accepted point fails here. This is the net that makes
//   the later "Brazil OFF = identical to today" claim VERIFIABLE rather than hoped.
//   It is a Feathers-style characterization test: it asserts what the code DOES
//   today, not what it "should" do.
//
// IMPORTANT — these expectations were generated by EVALUATING THE REAL MODULE,
// not by trusting the plan's prose. Where this file disagrees with the plan, the
// CODE wins (see the discrepancy notes below). Re-derive by running the module if
// you ever need to refresh; never hand-edit a boolean to make a future change pass
// (that would silence the regression this test exists to catch).
//
// THE REAL PREDICATE (verbatim from variaveisAmbiente.js, lat = coords[0], lng = coords[1]):
//   rect1:  coords[0] <  2.20  && coords[0] > -14.09  &&  coords[1] > -52.42 && coords[1] < -34.32
//   OR
//   rect2:  coords[0] < -14.18 && coords[0] > -32.66  &&  coords[1] > -55.55 && coords[1] < -38.06
//   ALL comparisons are STRICT ( < / > ), so a point EXACTLY on any edge is REJECTED.
//
// This file is deterministic and fast: a pure function, no network, no DOM, no timers.

import { describe, it, expect } from 'vitest';

import envVariables from
  '../src/app/components/compatibility/components/variaveisAmbiente.js';

const dentroLimites = envVariables.dentroLimites;

// ──────────────────────────────────────────────────────────────────────────
// Layer 1 — COARSE 1° GRID (broad-coverage backstop, NOT the precision mechanism)
//
// Per §5 M0: a coarse 1-degree grid over the union-envelope of the two rectangles
// (plus a ~2° margin so border-REJECT cells are captured too) is enough; a dense
// grid buys nothing on a two-rectangle OR'd predicate, and the gate runs ~10x.
//   lat:  +4 .. -34  step 1  → 39 rows
//   lng: -57 .. -33  step 1  → 25 cols
//   = 975 cells  (under the plan's explicit < ~1000 ceiling for a small, reviewable fixture)
//
// We freeze the CURRENT decision boundary as the set of grid cells that return TRUE
// today (everything else in the grid returns FALSE). The map below is the literal
// output of evaluating dentroLimites over the grid. Its shape is the two rectangles:
//   • lat  2 .. -14 → lng -52 .. -35   (rect1; integer lat -14 is inside because -14 > -14.09)
//   • lat -15 .. -32 → lng -55 .. -39   (rect2)
// The integer grid steps OVER the -14.18 .. -14.09 seam band; Layer 3 pins that seam
// at fractional latitudes (a coarse grid alone would miss a delegation silently
// closing the gap — exactly the §4.0 hazard).
const GRID_LAT_TOP = 4;
const GRID_LAT_BOTTOM = -34;
const GRID_LNG_LEFT = -57;
const GRID_LNG_RIGHT = -33;

// Frozen TRUE set: lat → sorted list of integer lng that return TRUE today.
// (Generated from the real module; any lat not listed has ZERO true cells in-grid.)
const FROZEN_TRUE = {
  2: [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  1: [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  0: [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-1': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-2': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-3': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-4': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-5': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-6': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-7': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-8': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-9': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-10': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-11': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-12': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-13': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-14': [-52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39, -38, -37, -36, -35],
  '-15': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-16': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-17': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-18': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-19': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-20': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-21': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-22': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-23': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-24': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-25': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-26': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-27': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-28': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-29': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-30': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-31': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  '-32': [-55, -54, -53, -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40, -39],
  // lat -33, -34: ZERO true cells (below rect2 floor -32.66).
};

function frozenExpectation(lat, lng) {
  const row = FROZEN_TRUE[String(lat)];
  return Array.isArray(row) && row.includes(lng);
}

describe('M0 geofence characterization — coarse 1° grid (broad backstop)', () => {
  it('matches the frozen decision boundary for EVERY grid cell (975 cells)', () => {
    const mismatches = [];
    let total = 0;
    for (let lat = GRID_LAT_TOP; lat >= GRID_LAT_BOTTOM; lat -= 1) {
      for (let lng = GRID_LNG_LEFT; lng <= GRID_LNG_RIGHT; lng += 1) {
        total += 1;
        const actual = dentroLimites([lat, lng]);
        const expected = frozenExpectation(lat, lng);
        if (actual !== expected) {
          mismatches.push(`[${lat}, ${lng}] expected ${expected}, got ${actual}`);
        }
      }
    }
    // Confirms the grid dimensions are what the fixture was frozen against.
    expect(total).toBe(975);
    // A SINGLE flipped cell (an M1 delegation changing the accepted set) lands here.
    expect(mismatches).toEqual([]);
  });

  it('characterizes the two-rectangle structure: rect1 wider-north, rect2 lower-west', () => {
    // rect1 owns the northern band (lat down to -14) over lng -52..-35.
    expect(dentroLimites([0, -45])).toBe(true);
    // rect2 owns the southern band, shifted WEST (reaches -55) but NOT as far east (-39).
    expect(dentroLimites([-25, -54])).toBe(true); // in rect2's western reach
    expect(dentroLimites([0, -54])).toBe(false); // rect1 does NOT reach lng -54
    expect(dentroLimites([-25, -36])).toBe(false); // rect2 does NOT reach lng -36
  });
});

// ──────────────────────────────────────────────────────────────────────────
// Layer 2 — RECTANGLE MATH (the precision mechanism: corners + on-edge + ±epsilon)
//
// Per §5 M0: for EACH rectangle, assert the 4 corners + a just-inside / just-outside
// pair (±epsilon) on each of the 4 edges. This characterizes the boundary exhaustively
// and is robust to grid phase (the grid can never land exactly on -14.09 etc.).
//
// KEY CHARACTERIZED FACT: edges are STRICT. A point EXACTLY on a corner or edge is
// REJECTED today. A future "<=" refactor would flip these and is caught here.
const EPS = 1e-4;

const RECT1 = { N: 2.20, S: -14.09, W: -52.42, E: -34.32 };
const RECT2 = { N: -14.18, S: -32.66, W: -55.55, E: -38.06 };

function assertRectangle(name, R, latMid, lngMid) {
  describe(`M0 rectangle math — ${name} (strict edges)`, () => {
    it('REJECTS all four corners (strict < / >, so on-edge is out)', () => {
      expect(dentroLimites([R.N, R.W])).toBe(false); // NW
      expect(dentroLimites([R.N, R.E])).toBe(false); // NE
      expect(dentroLimites([R.S, R.W])).toBe(false); // SW
      expect(dentroLimites([R.S, R.E])).toBe(false); // SE
    });
    it('REJECTS a point exactly ON each edge (mid-edge, strict)', () => {
      expect(dentroLimites([R.N, lngMid])).toBe(false); // on N edge
      expect(dentroLimites([R.S, lngMid])).toBe(false); // on S edge
      expect(dentroLimites([latMid, R.W])).toBe(false); // on W edge
      expect(dentroLimites([latMid, R.E])).toBe(false); // on E edge
    });
    it('ACCEPTS just INSIDE each edge (±epsilon)', () => {
      expect(dentroLimites([R.N - EPS, lngMid])).toBe(true); // inside of N
      expect(dentroLimites([R.S + EPS, lngMid])).toBe(true); // inside of S
      expect(dentroLimites([latMid, R.W + EPS])).toBe(true); // inside of W
      expect(dentroLimites([latMid, R.E - EPS])).toBe(true); // inside of E
    });
    it('REJECTS just OUTSIDE each edge (±epsilon)', () => {
      expect(dentroLimites([R.N + EPS, lngMid])).toBe(false); // outside of N
      expect(dentroLimites([R.S - EPS, lngMid])).toBe(false); // outside of S
      expect(dentroLimites([latMid, R.W - EPS])).toBe(false); // outside of W
      expect(dentroLimites([latMid, R.E + EPS])).toBe(false); // outside of E
    });
  });
}

// latMid/lngMid are interior points of each rectangle (used to probe a single edge
// while keeping the other axis comfortably inside).
assertRectangle('rect1', RECT1, -6, -43);
assertRectangle('rect2', RECT2, -23, -46);

// ──────────────────────────────────────────────────────────────────────────
// Layer 3 — §4.0 DIVERGENCE POINTS + the inter-rectangle SEAM (explicit, named)
//
// Each value below was VERIFIED against the real module (not the plan's prose).
describe('M0 §4.0 divergence points — REAL current dentroLimites output', () => {
  // §4.0 lists these as points where dentroLimites disagrees with the OTHER bounds
  // sources (BR_BBOX / the search viewport). M0 freezes what dentroLimites ITSELF
  // returns; a delegation to isInsideCountry('br') reading COUNTRY_BOUNDS.br would
  // flip several of these and MUST fail here.

  it('REJECTS extreme south [-33.7, -53.4] (Chuí/RS — dry BR land, but below rect2 floor -32.66)', () => {
    // Plan §4.0: rejected by dentroLimites, accepted by COUNTRY_BOUNDS.br. CODE agrees: false.
    expect(dentroLimites([-33.7, -53.4])).toBe(false);
  });

  it('REJECTS west Amazonas [-4.0, -58.0] (lng -58 is west of rect1 W=-52.42)', () => {
    // Plan §4.0: rejected by dentroLimites, accepted by COUNTRY_BOUNDS.br. CODE agrees: false.
    expect(dentroLimites([-4.0, -58.0])).toBe(false);
  });

  it('REJECTS west Acre [-9.0, -72.0] (far west of rect1 W=-52.42)', () => {
    // Plan §5 M0 lists this as a dentroLimites REJECT. CODE agrees: false.
    // (Note §4.0 prose separately says BR_BBOX W=-73.99 would ACCEPT west Acre; that
    //  is BR_BBOX, NOT dentroLimites. M0 only characterizes dentroLimites, which rejects.)
    expect(dentroLimites([-9.0, -72.0])).toBe(false);
  });

  it('REJECTS the origin [0, 0] (open ocean / off-continent sanity anchor)', () => {
    expect(dentroLimites([0, 0])).toBe(false);
  });

  // THE SEAM: rect1 floor is lat -14.09, rect2 ceiling is lat -14.18 (note rect2 uses
  // the more-negative bound). The open interval (-14.18 .. -14.09) is covered by
  // NEITHER rectangle inside the lng-overlap, so it is REJECTED. A country-aware
  // delegation could close this gap SILENTLY — these assertions stop that.
  describe('inter-rectangle latitude seam (-14.18 .. -14.09) inside the lng overlap', () => {
    const lngInOverlap = -45; // within both rect1 (-52.42..-34.32) and rect2 (-55.55..-38.06)
    it('REJECTS the seam midpoint [-14.135, -45]', () => {
      expect(dentroLimites([-14.135, lngInOverlap])).toBe(false);
    });
    it('REJECTS just below rect1 floor [-14.10, -45]', () => {
      expect(dentroLimites([-14.10, lngInOverlap])).toBe(false);
    });
    it('REJECTS just above rect2 ceiling [-14.17, -45]', () => {
      expect(dentroLimites([-14.17, lngInOverlap])).toBe(false);
    });
    it('ACCEPTS just INTO rect1 [-14.08, -45] (above the seam)', () => {
      expect(dentroLimites([-14.08, lngInOverlap])).toBe(true);
    });
    it('ACCEPTS just INTO rect2 [-14.19, -45] (below the seam)', () => {
      expect(dentroLimites([-14.19, lngInOverlap])).toBe(true);
    });
  });
});

// ──────────────────────────────────────────────────────────────────────────
// Layer 4 — a couple of unambiguous interior ANCHORS (real BR cities in-bounds today)
describe('M0 sanity anchors — real points accepted today', () => {
  it('ACCEPTS João Pessoa-ish [-7.1, -34.8] (inside rect1)', () => {
    expect(dentroLimites([-7.1, -34.8])).toBe(true);
  });
  it('ACCEPTS São Paulo-ish [-23.55, -46.63] (inside rect2)', () => {
    expect(dentroLimites([-23.55, -46.63])).toBe(true);
  });
});
